### ISSUE TITLE
GNU License

### ISSUE THREAD

**Issue by ribbles** [sportarchive/aws-lambda-python-local#1]
Hi,

This project is set up to be the basis of writing additional code on top of (as compared to an external tool). In reality, this would mean branching the aws-lambda-python-local project and writing our own code on top of it, mingling the two code-bases. This runs afoul of the GNU license you have applied to it. How are you keeping your lambda functions and swagger definition separate?

b) You must cause any work that you distribute or publish, that in
    whole or in part contains or is derived from the Program or any
    part thereof, to be licensed as a whole at no charge to all third
    parties under the terms of this License.

**Comment by koxon** [comment]
Hi, 

I understand your point. I could change the license. You could also keep your lambda in a separate git submodule.

**Comment by ribbles** [comment]
This would require a .gitmodule file within the aws-lambda-python-local project.

**Comment by koxon** [comment]
Now MIT licene
